name: CI
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions-hub/stylelint@v1.1.6
      - uses: actions/setup-node@v4
      - run: npx stylelint "**/*.css"
